// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObrasBibliograficasAPI.Models;

namespace ObrasBibliograficasAPI.Migrations
{
    [DbContext(typeof(ObrasBibliograficasAPIContext))]
    partial class ObrasBibliograficasAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("ObrasBibliograficasAPI.Models.ObrasBibliograficas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAutor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ObrasBibliograficas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeAutor = "Marcelo da Silva Sousa"
                        },
                        new
                        {
                            Id = 2,
                            NomeAutor = "João da Silva"
                        },
                        new
                        {
                            Id = 3,
                            NomeAutor = "Paulo Coelho"
                        },
                        new
                        {
                            Id = 4,
                            NomeAutor = "Celso de Araujo"
                        },
                        new
                        {
                            Id = 5,
                            NomeAutor = "Guimaraes"
                        },
                        new
                        {
                            Id = 6,
                            NomeAutor = "Roberto Ferreira Neto"
                        },
                        new
                        {
                            Id = 7,
                            NomeAutor = "Anderson Gomes Souza Filho"
                        },
                        new
                        {
                            Id = 8,
                            NomeAutor = "Matheus Alves"
                        },
                        new
                        {
                            Id = 9,
                            NomeAutor = "Amanda Lima"
                        },
                        new
                        {
                            Id = 10,
                            NomeAutor = "Isabela Feranandes Rocha"
                        },
                        new
                        {
                            Id = 11,
                            NomeAutor = "Vinicius Matheus da Silva Neto"
                        },
                        new
                        {
                            Id = 12,
                            NomeAutor = "Rafael Bezerra de Santos"
                        },
                        new
                        {
                            Id = 13,
                            NomeAutor = "Ingrid"
                        },
                        new
                        {
                            Id = 14,
                            NomeAutor = "José Junior"
                        },
                        new
                        {
                            Id = 15,
                            NomeAutor = "Daniela Costa Filha"
                        },
                        new
                        {
                            Id = 16,
                            NomeAutor = "Guilherme Borges de Souza"
                        },
                        new
                        {
                            Id = 17,
                            NomeAutor = "Fernando"
                        },
                        new
                        {
                            Id = 18,
                            NomeAutor = "Karina de Gomes"
                        },
                        new
                        {
                            Id = 19,
                            NomeAutor = "Everton Filho"
                        },
                        new
                        {
                            Id = 20,
                            NomeAutor = "Gisele Ferreira Santos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
